const menu = [
  {
    id: 1,
    title: "Idly Sambar",
    category: "breakfast",
    price: 40,
    img: "./images/IdlySambar.jpg",
    desc: `Fresh and authentic SouthIndian style Idly and Sambar to start your day `,
  },
  {
    id: 2,
    title: "Masala Dosa",
    category: "breakfast",
    price: 45,
    img: "./images/MasalaDosa.jpg",
    desc: `Delicious and authentic SouthIndian style Masala dosa to start your day `,
  },
  {
    id: 5,
    title: "Biriyani",
    category: "lunch",
    price: 160,
    img: "./images/Biriyani.jpg",
    desc: `Long-grained rice (like basmati) flavored with fragrant spices such as saffron and layered with chicken. The dish is then covered, and then the biryani is cooked over a low flame`,
  },
  {
    id: 10,
    title: "Curd rice",
    category: "dinner",
    price: 50,
    img: "./images/CurdRice.jpg",
    desc: ` Curd rice is nothing but curd (yogurt) mixed with cooked rice, herbs and then tempered. `,
  },
  {
    id: 3,
    title: "Vanilla milkshake",
    category: "drinks/shakes",
    price: 60,
    img: "./images/VanillaMilkshake.jpg",
    desc: `Treat yourself to an indulgent, creamy vanilla milkshake with our classic recipe. This easy drink is perfect for customising with indulgent toppings`,
  },
  {
    id: 4,
    title: "Puliyogare",
    category: "breakfast",
    price: 35,
    img: "./images/Puliyogare.jpg",
    desc: `an authentic and traditional rice-based recipe made with tamarind extract and dry spices. `,
  },
  {
    id: 6,
    title: "Oreo dream",
    category: "drinks/shakes",
    price: 70,
    img: "./images/OreoMilkshake.jpeg",
    desc: ` A super easy milkshake made with vanilla ice cream, milk, and Oreo cookies!  This sweet treat is a hit with the whole family on a hot day!`,
  },
  {
    id: 7,
    title: "Nimbu Soda",
    category: "drinks/shakes",
    price: 30,
    img: "./images/Nimbu_Soda.jpg",
    desc: `Nimbu Soda is a popular Indian drink flavoured with lemon along with some, sugar and soda. `,
  },
  {
    id: 8,
    title: "Paratha",
    category: "lunch",
    price: 50,
    img: "./images/Paratha.jpg",
    desc: `Plain paratha or tawa paratha is an Indian flatbread made using whole wheat flour `,
  },
  {
    id: 9,
    title: "SouthIndian Meals",
    category: "lunch",
    price: 65,
    img: "./images/SouthMeals.jpg",
    desc: `Kosambari (south Indian salad), Pickle, Palya (vegetable side dish), Raita or gojju (vegetable cooked in tamarind juice), desserts, fried dishes, Thovve (cooked dal), huli (a thick broth of lentils and vegetables), Chitranna (rice-based dish), plain rice.`,
  },

  {
    id: 11,
    title: "Fried Rice",
    category: "dinner",
    price: 60,
    img: "./images/FriedRice.jpg",
    desc: `Fried Rice is a combination of long grained rice, mixture of warm peas, carrots and onions with scrambled eggs mixed all together `,
  },
  {
    id: 12,
    title: "Coffee",
    category: "drinks/shakes",
    price: 30,
    img: "./images/Coffee.jpg",
    desc: `Coffee is a brewed drink prepared from roasted coffee beans, the seeds of berries from certain Coffea species `,
  },
  {
    id: 13,
    title: "Tea",
    category: "drinks/shakes",
    price: 30,
    img: "./images/Tea.jpg",
    desc: `Tea is an aromatic beverage prepared by pouring hot or boiling water over cured or fresh tea leaves `,
  },
];

export default menu;
